
  image: "openjdk:8-jdk"
  variables: 
    GIT_DEPTH: "0"
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
before_script: 
  - "chmod +x gradlew"
buildJob: 
  script: 
    - "./gradlew build"
  stage: build
only: 
  - merge_requests
  - master
  - develop
script: 
  - sonar-scanner
  - "apk add bash"
  - "bash <(curl -s https://codecov.io/bash) -t fa4ea4b0-402c-4d17-962f-0842cee2a73f"
sonarcloud-check: 
  cache: ~
  dependencies: 
    - testJob
  image: "sonarsource/sonar-scanner-cli:latest"
  key: "${CI_JOB_NAME}"
  paths: 
    - .sonar/cache
  stage: code-analysis
stages: 
  - build
  - test
  - code-analysis
testJob: 
  artifacts: 
    paths: 
      - build/reports/jacoco
  script: 
    - "./gradlew check"
    - "./gradlew codeCoverageReport"
  stage: test
